### ISSUE TITLE
How can I install this mod?

### ISSUE THREAD

**Issue by plyuspavel** [Hallam9K/RedemptionAlpha#4]
Hello! We want to play your mod in Terraria 1.4 and installed tModLoader v 0.12.1.4. I tried to put these files in all the folders in C:\Users\{username}\Documents\My Games\Terraria\ModLoader but nothing happened and it isn't displayed in mod list. 
Could you please add detailed instruction how to install your mod? Thanks

**Comment by Hallam9K** [comment]
download as .zip, extract it, rename the folder to just Redemption instead of RedemptionAlpha, then put the folder inside Documents\My Games\Terraria\ModLoader\Beta\Mod Sources

**Comment by Walparr** [comment]
![image](https://user-images.githubusercontent.com/87207333/152513313-8548511a-3801-4c66-bd90-b6f374628419.png)
i followed the steps but it doesnt appear anywhere in game, do i need to do something else or...?

**Comment by Serb20** [comment]
go to workshop, develop mods, then build and reload the mod

**Comment by Walparr** [comment]
:o thanks
